# ETL, Analysis, and Visualization

**Nicolás Gallardo**

# Index

- [Abstract](#Abstract)
- [1. Introduction](#1.-Introduction)
- [2. Extract-Transform-Load](#2.-Extract-Transform-Load)
    - [2.1 The ETL Process](#2.1-The-ETL-Process)
    - [2.2 Data Exploration](#2.2-Data-Exploration)
    - [2.3 Data Preparation](#2.3-Data-Preparation)
    - [2.4 Read the Data Using Python](#2.4-Reading-the-Data-Using-Python)
         - [2.4.1 Reading Sample Data](#2.4.1-Reading-Sample-Data)
         - [2.4.2 Reading the MRST Data](#2.4.2-Reading-the-MRST-Data)
    - [2.5 Writing an Installation Script](#2.5-Writing-an-Installation-Script)
- [3. Analysis and Visualization](#3.-Project-Description)
    - [3.1 Running Queries in MySQL Workbech](#3.1-Running-Queries-in-MySQL-Workbech)
    - [3.2 Running Queries From Python](#3.2-Running-Queries-From-Python)
    - [3.3 Explore Trends](#3.3-Explore-Trends)
    - [3.4 Explore Percentage Change](#3.4-Explore-Percentage-Change)
    - [3.5 Explore Rolling Time Windows](#3.5-Explore-Rolling-Time-Windows)
- [Conclusion](#Conclusion)
- [References](#References)

[Back to top](#Index)


##  Abstract

This is a brief description (150 words or less) of your analysis and the results of your model. Complete this portion of the template after you are done working on your project.

This project was achieved in extracting and transforming an Excel file using Pandas, to create a ready-to-use CSV file to be loaded into an SQL database table with the aid of a Python script. 

Then, a series of analysis and plots were created through python using *mysql.connector* library and the *matplotlib* library to visualize the analysis, which were discussed and commented. The concepts of Trend, Percentage Change and Window Rolling were explored with the analysis.

[Back to top](#Index)


## 1. Introduction

Introduce your project using 300 words or less. Describe all the processes you followed to create your ETL, Analysis, and Visualization project. Start by summarizing the steps that you intend to perform and then elaborate on this section after you have completed your project.

The first step was extracting the data from an Excel file, using the *read_excel* Pandas function. Then, a series of steps were performed to transform the data, that came in many different sheets, into just one sheet. This was a new dataframe, which was then exported as a CSV file. 

This CSV file was then loaded into a table. The table was created using *mysql.connector*, and the csv file was added into the table using the same library and the *csv* library in Python to help reading the CSV file. 

After that, a series of queries were created through Python and visualized with *matplotlib* library. This queries also were created to visualize and comprehend the concepts of trend, percentage change and window rolling, which all were performed through SQL.

[Back to top](#Index)

## 2. Extract-Transform-Load

For each of the sections below, include a description of the steps you followed. Whenever possible, include screenshots of your code or program windows to demonstrate your steps.

[Back to top](#Index)

### 2.1 The ETL Process

Describe, using your own words, the key steps to perform ETL on the provided MRTS dataset.

The key steps to perform ETL on the MRTS dataset are the following ones:

- Extracting the dataset into a dataframe using Pandas library, specifically the *read_excel* function. 
- Transforming the data into a structure similar to a predefined table of a database, using Pandas dataframes. This way, the data can be loaded easily into the table with the type structures needed.
- Loading the new transformed dataset into a database using a Python script.

[Back to top](#Index)

### 2.2 Data Exploration

Describe the MRTS dataset and the data that it contains. Feel free to do some research online to get more information about the dataset. This step is fundamental and it will help you with the development of your project.

This dataset is about the Monthly Retail Trade Sales of Food and Retail services from the US. The data is collected from the years 1992 to February 2021. This information comes officially from the webpage [Census](https://www.census.gov/), which is an agency of the U.S. Department of Commerce. 

The information contained in this dataset is of different Retail and Food sales for every month of the different years (except for 2021 which is not completed). The data is brought in million of dollars. It's also estimated and adjusted.

The dataset can be checked in the file inside the following route: */data/mrtsales92-present.xls*

[Back to top](#Index)

### 2.3 Data Preparation

Describe which modifications you want to perform on your dataset so that it’s ready for analysis. A few obvious ones are suggested in the video, but come up with at least one modification on your own as well.

The main modification that was implemented in the data was to get all the data into a single sheet. The dataset used had all the information divided into many sheets, depending on the year. This is not very practical when loading into a table in the database. So, the most important step was getting all the information from all the years into just one big file.

Another important step, was to get all the data cleaned, and just the information used into a CSV file. In other words, the only information that had to be loaded was the data itself, and the Excel file included a lot of notations titles that had to be removed. 

After getting the new dataset containing all the data within one page, another important steps were executed: removing NaN, ordering indexes, ordering format and type structure, etc. 

The whole extract and transformation steps can be found in the file */ETC(extraction-transformation.ipynb* which is a Jupyter Notebook dealing with all the steps commented.

[Back to top](#Index)

### 2.4 Read the Data Using Python

Describe briefly how Python can be used to read CSV files.

Python has a built-in function called open() which can be used to read different type of files (it also can be used to write into files). 

Then, the *CSV* library can be used to make the read of a CSV file easier.

[Back to top](#Index)

### 2.4.1 Reading Sample Data

Describe the sample dataset that you have defined to test your Python script to read CSV files and explain how you used Python to read it.

A sample data to test out the script was not used, instead, the transformed CSV file was implemented directly into the database.

[Back to top](#Index)

### 2.4.2 Reading the MRTS Data

Describe how to read the MRTS CSV file using a Python script.

The data was read using the following script:


```
# The CSV file is read to load it into the database.
with open("data/transformedmrtsales92-present.csv", mode='r') as csv_data:
    reader = csv.reader(csv_data, delimiter=',')
```

[Back to top](#Index)

### 2.5 Writing an Installation Script

Describe how you wrote a Python installation script to read your dataset in MySQL WorkBench.

The complete installation script to connect the database, create the table to use, read the CSV file and insert into the table the values of the CSV file was the following:

import mysql.connector
import csv

```  
# Connection is created with the database
con = mysql.connector.connect(user='root', password='1234', host='localhost', database='mit')
	
# A cursor is instanced
cursor = con.cursor()

# The table is dropped in case it exists.
cursor.execute("DROP TABLE IF EXISTS MRTS")

# A query is written to create the table within the database.
sql_query ='''CREATE TABLE MRTS(
   id VARCHAR(25) NOT NULL,
   id_group INT NOT NULL,
   business_description VARCHAR(100),
   date DATE NOT NULL,
   sales INT NULL,
   status VARCHAR(20) NOT NULL
  )'''

# The query is executed.
cursor.execute(sql_query)
print("Table created successfully")

cursor = con.cursor()

# The CSV file is read to load it into the database.
with open("data/transformedmrtsales92-present.csv", mode='r') as csv_data:
    reader = csv.reader(csv_data, delimiter=',')
    # The header is ignored when uploaded into the database.
    next(reader, None)
    csv_data_list = list(reader)
    for row in csv_data_list:
      # The NaN values, converted by Pandas into an empty string, are specified as None values into the database.
      for i in range(len(row)):
          if row[i] == '':
              row[i] = None        
      # The query that inserts the dataset into the database is executed.
      cursor.execute("""
                  INSERT INTO MRTS(
                  id, id_group, business_description, date, sales, status)
                  VALUES(%s,%s,%s,%s,%s,%s)""",
                  (row[0], row[1], row[2], row[3], row[4], row[5]))
con.commit()
cursor.close()
con.close()
print("Done")
```

The script can be found in the route */ETL(load).py*


[Back to top](#Index)

## 3. Analysis and Visualization

For each of the sections below, make sure you include a description of the steps you followed. Whenever possible, include screenshots of your code or program windows to demonstrate your steps.

Here, describe the differences, advantages, and disadvantages of running *queries* against your dataset using the MySQL Workbench or a Python environment.

[Back to top](#Index)

### 3.1 Running Queries in MySQL Workbech

Describe which *queries* you ran against the MRTS dataset in MySQL Workbench to verify that everything worked as expected.

The following queries were used to check if the data was loaded correctly:

```
USE mit;
SELECT COUNT(*)
FROM mrts;
```
This one was used to verify if all the rows were added into the table, which were 20301 rows. The result of this query is 20300, which is right because the header was ignored when inserting the data.

The second query used was the following:

```USE mit;
SELECT * FROM mrts
WHERE  status = "NaN";
```
This query was used to check if the NaN values of Sales were correctly inserted as NULL, which was shown in the workbench.

These queries can be checked in the route */SQL Queries/3.1/*

[Back to top](#Index)

### 3.2 Running Queries From Python

Describe how you tested the previous *queries* on the the MRTS dataset using a Python script and the Terminal window.

The queries were tested using the *mysql.connector* library. Then, the queries were run in the terminal with the python command.

They were successful as they gave the same results as the SQL ones in the workbench.

The queries were the following ones: 

```import mysql.connector

  
# Connecting with MySql
con = mysql.connector.connect(user='root', password='1234', host='localhost', database='mit')
	
# Using cursor() method to create cursor object
cursor = con.cursor()

sql = ("""
SELECT * FROM mrts
WHERE  status = "NaN";
""")
cursor.execute(sql)
for row in cursor.fetchall():
    print(row)

cursor.close()
con.close()

----------------------------

import mysql.connector

  
# Connecting with MySql
con = mysql.connector.connect(user='root', password='1234', host='localhost', database='mit')
	
# Using cursor() method to create cursor object
cursor = con.cursor()

sql = ("""
SELECT COUNT(*)
FROM mrts;
""")
cursor.execute(sql)
for row in cursor.fetchall():
    print(row)

cursor.close()
con.close()
```

The queries can be found in the route */Python Queries/3.2/*

[Back to top](#Index)

### 3.3 Explore Trends

Describe which *queries* you wrote the explore the differences in trends between various categories in your data.

In your submission make sure to answer the following:

- What is an economic trend and why is it considered an important measure to predict quantities, like spending patterns?
- What is the trend of the retail and food services categories? Can this data be displayed clearly or do you need to adjust some parameters to reduce extraneous details and be able to visualize a clean trend?
- When comparing businesses like bookstores, sporting goods stores, and hobbies, toys, and games stores, what is the highest trend of all of these options? Which one grew faster? Which one is higher? Is there a seasonal pattern? Were there any changes in 2020? Which is better, monthly or yearly?

a) The following definition can be found in this [article](https://www.bartleby.com/subject/business/concepts/economic-trends):
>An economic trend is the long-term direction of an economy. The trend can go up, down, or sideways. An upward trend means the economy is growing and wages are rising. A downward trend means the economy is shrinking and unemployment is increasing. A sideways trend means the economy is neither growing nor shrinking.

b) To get the data plotted for this question, the next code was used:

```
import mysql.connector
import matplotlib.pyplot as plt
  
# Connecting with MySql
con = mysql.connector.connect(user='root', password='1234', host='localhost', database='mit')
	
# Using cursor() method to create cursor object
cursor = con.cursor()

# The query is written
sql = ("""SELECT date, SUM(sales) FROM mrts
WHERE id = "722" AND date like "%-01-%"
GROUP BY date;""")
cursor.execute(sql)

# The information brought by the query is fetched into the following variables:
year1 = []
sales1 = []
for row in cursor.fetchall():
    year1.append(row[0])
    sales1.append(row[1])

# The query is written
sql = ("""SELECT date, SUM(sales) FROM mrts
WHERE id_group = "452" AND date LIKE "%-01-%"
GROUP BY date""")
cursor.execute(sql)

# The information brought by the query is fetched into the following variables:
year2 = []
sales2 = []
for row in cursor.fetchall():
    year2.append(row[0])
    sales2.append(row[1])

cursor.close()
con.close()

# A graph showing the data is plotted.
plt.plot(year1, sales1, label="Food Services")
plt.plot(year2, sales2, label="Retail Services")

plt.xlabel('Year')
plt.ylabel('Sales in Millions of Dollars')
plt.title("Food Services vs Retail Services Trends")


plt.legend()

plt.show()
```

Resulting in the next plot: 
![hi](assets/images/figure_1.webp)

As it can be seen in this image, both services have a positive trend during time. However, in 2020, and probably because of the [COVID-19 pandemic](https://www.worldbank.org/en/publication/wdr2022/brief/chapter-1-introduction-the-economic-impacts-of-the-covid-19-crisis), there was a break in trend for both services, being even more positive for the retail services sales and becoming negative for the food services sales. 

This data was not displayed well when plotted by month, so there had to be transformation in the query, which was converting the date into a year display and adding the sales of every month to get the total of it.

c) The following code was completed to get the plot asked:

```
import mysql.connector
import matplotlib.pyplot as plt
  
# Connecting with MySql
con = mysql.connector.connect(user='root', password='1234', host='localhost', database='mit')
	
# Using cursor() method to create cursor object
cursor = con.cursor()

# The query is written
sql = ("""SELECT date, SUM(sales) FROM mrts
WHERE id = "45111" AND date like "%-01-%"
GROUP BY date;""")
cursor.execute(sql)

# The information brought by the query is fetched into the following variables:
year1 = []
sales1 = []
for row in cursor.fetchall():
    year1.append(row[0])
    sales1.append(row[1])

# The query is written
sql = ("""SELECT date, SUM(sales) FROM mrts
WHERE id = "45112" AND date LIKE "%-01-%"
GROUP BY date;""")
cursor.execute(sql)
# The information brought by the query is fetched into the following variables:
year2 = []
sales2 = []
for row in cursor.fetchall():
    year2.append(row[0])
    sales2.append(row[1])

# The query is written
sql = ("""SELECT date, SUM(sales) FROM mrts
WHERE  id = "451211" AND date LIKE "%-01-%"
GROUP BY date;""")
cursor.execute(sql)

# The information brought by the query is fetched into the following variables:
year3 = []
sales3 = []
for row in cursor.fetchall():
    year3.append(row[0])
    sales3.append(row[1])

cursor.close()
con.close()

# A graph showing the data is plotted
plt.plot(year1, sales1, label="Sporting good stores")
plt.plot(year2, sales2, label="Hobby, toy, and game stores")
plt.plot(year3, sales3, label="Book stores")

plt.xlabel('Year')
plt.ylabel('Sales in Millions of Dollars')
plt.title("Trends of question 3.3.3, by January")


plt.legend()

plt.show()
```

Getting the following plot displayed:

![figure 2](assets/images/figure_2.png)

As it can be seen here, the trend was positive for all the different retail subtypes, up until 2008, when the [stock market crashed](https://en.wikipedia.org/wiki/2007%E2%80%932008_financial_crisis), where the Bookstores have had a decline in sales since, not showing any impact from the Pandemic. In contrast, the "Sporting Good Stores" and the "Hobby, Toy, and Game Stores" had an exponential growth when the pandemic hit in 2020. This analysis was made taking account only January of 2021, as it was the only month with all years available.

Python queries can be found in route */Python Queries/3.3/*

[Back to top](#Index)

### 3.4 Explore Percentage Change

Describe which *queries* you wrote to explore the differences in trends between various categories in your data.

In your submission make sure to answer the following:

- In economics, what is the percentage change and why is it considered an important measure to predict quantities like spending patterns?
- Consider the women's clothing and men's clothing businesses and their percentage change. How are these two businesses related? For each of the two businesses, what is the percentage of contribution to the whole and how does it change over time?

a) The definition can be found in the next article from [Investopedia](https://www.investopedia.com/terms/p/percentage-change.asp):
>Percentage change is used for many purposes in finance, often to represent the price change of a stock over time, expressed as a percentage. To calculate percentage change, first, subtract the earlier stock value from the later stock value; then divide that difference by the earlier value, and finally, multiply the result by 100.
>- Percentage change is used for many purposes in finance, most notably to track the price change of stocks and market indexes.
>- Change as a percentage is also used to compare the values of different currencies.
>- Percentage change also can be found in balance sheets with comparative financial statements.
>- How to calculate percentage change differs slightly depending on whether it is an increase or a decrease.

b) The following code was written to get the first question: 
```
import mysql.connector
import matplotlib.pyplot as plt
  
# Connecting with MySql
con = mysql.connector.connect(user='root', password='1234', host='localhost', database='mit')
	
# Using cursor() method to create cursor object
cursor = con.cursor()

# The information brought by the query is fetched into the following variables:
sql = ("""SELECT b.y,
(cast(b.sales-a.sales as float)/a.sales*100) as PctChange
FROM (SELECT Year(date) as y, SUM(sales) as sales FROM mrts
WHERE id = "44811" AND date NOT LIKE "%2021-%"
GROUP BY y) a 
LEFT JOIN (SELECT Year(date) as y, SUM(sales) as sales FROM mrts
WHERE id = "44811" AND date NOT LIKE "%2021-%"
GROUP BY y) b
ON (a.y + 1 = b.y)
ORDER BY a.y; """)
cursor.execute(sql)

# The query is written
year1 = []
sales1 = []
for row in cursor.fetchall():
    year1.append(row[0])
    sales1.append(row[1])

# The query is written
sql = ("""SELECT b.y,
(cast(b.sales-a.sales as float)/a.sales*100) as PctChange
FROM (SELECT Year(date) as y, SUM(sales) as sales FROM mrts
WHERE id = "44812" AND date NOT LIKE "%2021-%"
GROUP BY y) a 
LEFT JOIN (SELECT Year(date) as y, SUM(sales) as sales FROM mrts
WHERE id = "44812" AND date NOT LIKE "%2021-%"
GROUP BY y) b
ON (a.y + 1 = b.y)
ORDER BY a.y; """)
cursor.execute(sql)

# The information brought by the query is fetched into the following variables:
year2 = []
sales2 = []
for row in cursor.fetchall():
    year2.append(row[0])
    sales2.append(row[1])


cursor.close()
con.close()

# A graph showing the data is plotted.

plt.plot(year1, sales1, label="Men's Clothing")
plt.plot(year2, sales2, label="Women's Clothing")

plt.xlabel('Year')
plt.ylabel('Percentage Change (%)')
plt.title("Clothing Percentage Change By Year")


plt.legend()

plt.show()

```

The result up until 2020 is shown in the following graph:
![hi](assets/images/figure_3.png)

As it can be drawn from the plot, the percentage change varied between -10% and 10% during the years sampled.. However, when the pandemic hit, the Women's Clothing sales went down to -30% approximately, and the Men's Clothing went down to -60%. These two business are related to Clothing Stores in general.

To get the relation and contribution to it, the next code was written:

```
import mysql.connector
import matplotlib.pyplot as plt
  
# Connecting with MySql
con = mysql.connector.connect(user='root', password='1234', host='localhost', database='mit')
	
# Using cursor() method to create cursor object
cursor = con.cursor()

# A graph showing the data is plotted.
sql = ("""SELECT b.y,
(cast(a.sales as float)/b.sales*100) as PctChange
FROM (SELECT Year(date) as y, SUM(sales) as sales FROM mrts
WHERE id = "44811" 
GROUP BY y) a 
LEFT JOIN (SELECT Year(date) as y, SUM(sales) as sales FROM mrts
WHERE id = "448" 
GROUP BY y) b
ON (a.y = b.y)
ORDER BY a.y;""")
cursor.execute(sql)

# The information brought by the query is fetched into the following variables:
year1 = []
sales1 = []
for row in cursor.fetchall():
    year1.append(row[0])
    sales1.append(row[1])

# The query is written
sql = ("""SELECT b.y,
(cast(a.sales as float)/b.sales*100) as PctChange
FROM (SELECT Year(date) as y, SUM(sales) as sales FROM mrts
WHERE id = "44812" 
GROUP BY y) a 
LEFT JOIN (SELECT Year(date) as y, SUM(sales) as sales FROM mrts
WHERE id = "448" 
GROUP BY y) b
ON (a.y = b.y)
ORDER BY a.y;""")
cursor.execute(sql)

# The information brought by the query is fetched into the following variables:
year2 = []
sales2 = []
for row in cursor.fetchall():
    year2.append(row[0])
    sales2.append(row[1])


cursor.close()
con.close()

# A graph showing the data is plotted.
plt.plot(year1, sales1, label="Men's Clothing")
plt.plot(year2, sales2, label="Women's Clothing")

plt.xlabel('Year')
plt.ylabel('Percentage From Total (%)')
plt.title("Percentage From Clothing Sales")


plt.legend()

plt.show()

```

The results are shown:
![hi](assets/images/figure_4.png)

It can be noticed that percentage of contribution has been decreasing through time. The Men's Clothing sales percentage has gone from being 8% to 4% approximately. The Women's Clothing sales percentage has gone from 26% to 14% approximately, having a sharp decline between 1992 to 1998. 

Python queries can be found in route */Python Queries/3.4/*

[Back to top](#Index)

### 3.5 Explore Rolling Time Windows


Describe which *queries* you wrote to explore the differences in trends between various categories in your data.

In your submission, make sure to answer the following:

- In economics, what is the rolling time window and why is it considered an important measure to predict quantities like spending patterns?
- Consider at least two businesses of your own from the MRTS data. Which *queries* did you write to analyze and produce graphs of rolling time windows for the chosen categories?

a)The definition of rolling windows in SQL is expressed as the following for this [article](https://www.coginiti.co/tutorials/intermediate/sql-window-functions/):
>A window function is a type of SQL function that performs a calculation across a set of rows related to the current row. This set of rows is called a “window”. The window can be defined in many ways, such as by specifying a range of rows or grouping rows based on a common attribute. For example, you might use a window function to calculate the running total of sales for each product or rank customers based on their purchase history.

b) Two variables were chosen: the Clothing Sales and the Motor Vehicles Sales.

For the Clothing Sales, the next code was written:
```
import mysql.connector
import matplotlib.pyplot as plt
  
# Connecting with MySql
con = mysql.connector.connect(user='root', password='1234', host='localhost', database='mit')
	
# Using cursor() method to create cursor object
cursor = con.cursor()

# The query is written
sql = """SELECT
    date,
    sales/(AVG(sales) OVER(PARTITION BY YEAR(date))) * 100 - 100 as month_comparison_avg,
    sales/(SUM(sales) OVER(PARTITION BY YEAR(date))) * 100 as month_contribution
FROM mrts
WHERE id = "448" AND date like "%2018%";"""
cursor.execute(sql)

# The information brought by the query is fetched into the following variables:
date = []
month_comparison = []
month_contribution = []
for row in cursor.fetchall():
    date.append(row[0])
    month_comparison.append(row[1])
    month_contribution.append(row[2])

# A graph showing the data is plotted.
plt.plot(date, month_comparison, label="Month Percentage vs Month Average")
plt.plot(date, month_contribution, label="Month Sale Percentage")

plt.xlabel('Year')
plt.ylabel('Percentage (%)')
plt.title("Clothing Sales - 2018")


plt.legend()

plt.show()
```

Resulting in the following plot:
![hi](assets/images/figure_5.png)

As it can be seen in the plot, the sales were in a low during the first quarter of the year 2008, and they were in a peak during the 4th quarter of the year. This indicates that clothing sells better during the christmas season, and it sells much better than the average contribution of the month. 

For the Motor Vehicle Sales, the following was written:

```
import mysql.connector
import matplotlib.pyplot as plt
  
# Connecting with MySql
con = mysql.connector.connect(user='root', password='1234', host='localhost', database='mit')
	
# Using cursor() method to create cursor object
cursor = con.cursor()

# The query is written
sql = """SELECT
    date,
    sales/(AVG(sales) OVER(PARTITION BY YEAR(date))) * 100 - 100 as month_comparison_avg,
    sales/(SUM(sales) OVER(PARTITION BY YEAR(date))) * 100 as month_contribution
FROM mrts
WHERE id = "441" AND date like "%2018%";"""
cursor.execute(sql)

# The information brought by the query is fetched into the following variables:
date = []
month_comparison = []
month_contribution = []
for row in cursor.fetchall():
    date.append(row[0])
    month_comparison.append(row[1])
    month_contribution.append(row[2])

# A graph showing the data is plotted.

plt.plot(date, month_comparison, label="Month Percentage vs Month Average")
plt.plot(date, month_contribution, label="Month Sale Percentage")

plt.xlabel('Year')
plt.ylabel('Percentage (%)')
plt.title("Motor Vehicles Sales - 2018")


plt.legend()

plt.show()
```

Resulting in the following plot:
![hi](assets/images/figure_6.png)
In this case, the differences between sales within the months is not as sharp as the one in the Clothing Sales, and they're relatively similar.

Python queries can be found in route */Python Queries/3.5/*

[Back to top](#Index)

## Conclusion

Describe your conclusions. Which one of the businesses considered seems like it's going to attract the least spending? Which business seems likely to attract the most spending?

The general conclusiones are:
- ETL is a process to improve a dataset information into a cleaner form, for it to be ready to be analyzed.
- Pandas is a library that allows to transform and extract information from a file easily.
- Python and the mysql.connector library allow for an easy script to create and load data into a SQL database.
- Visualization in Python with SQL queries allow to create information that would be harder to achieve through another type of Python libraries.

According to the graphics and analysis, the retail stores, as a whole, are the ones that have kept a positive trend, for a large margin. On the other hand, the book stores sales have been declining since 2008 and they are likely not to attract the most spending.


[Back to top](#Index
)
## References

Add all references you used to complete this project.


- Kento, Will. "How to Calculate the Percentage Change" Investopedia. Dotdash Meredith. January 23, 2024. https://www.investopedia.com/